export { type } from './type'
export { undef, isUndef, isUndefined } from './undef'
export { bool, isBool, isBoolean } from './bool'
export { num, number, isNum, isNumber } from './num'
export { str, isStr, isString } from './str'
export { bigint, isBigInt } from './bigint'
export { symbol, isSymbol } from './symbol'
export { obj, object, isObj, isObject } from './obj'
